/* Generated by SMSNOW protocol CodeGen on Wed Aug 03 12:54:15 IST 2016. 

0 2 Binary trailerLenLL 4
2 2 Binary ZZ 0
*/
package com.smsnow.adaptation.dto.common;

import com.smsnow.adaptation.protocol.Protocol;
import java.io.Serializable;
import com.smsnow.adaptation.protocol.Format;
import com.smsnow.adaptation.protocol.Attribute;

@Protocol(name = "ITOCTRAILER")
public class ITOCTrailer implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.BINARY, offset = 0, length = 2, constant = "4")
	private short trailerLenLL;
	@Format(attribute = Attribute.BINARY, offset = 2, length = 2, constant = "0")
	private short zZ;

	public short getTrailerLenLL() {
		return trailerLenLL;
	}

	public void setTrailerLenLL(short trailerLenLL) {
		this.trailerLenLL = trailerLenLL;
	}

	public short getZZ() {
		return zZ;
	}

	public void setZZ(short zZ) {
		this.zZ = zZ;
	}

	public ITOCTrailer() {
	}
}