/* Generated by SMSNOW protocol CodeGen on Thu Aug 04 14:39:49 IST 2016. 

458 8 Text UserLogonID
466 1 Text LogonStatus
467 30 Text UserName
497 10 Text UserPhone
507 5 Text RespOrg
512 50 Text UpdateList
562 50 Text ViewList
612 1 Text UserClass
613 8 Text UserGroup
621 4 Numeric MaximumLogonAttempts
625 1 Text NUSPermissions
626 1 Text CADPermissions
627 1 Text CPRPermissions
628 1 Text LADPermissions
629 1 Text TRQPermissions
630 1 Text AOSLabelPermissions
631 3 numeric TimeoutInterval
634 1 Text FCC_Flag
635 1 Text CRAPermissions
636 1 Text CRRPermissions
637 1 Text NPAPermissions
638 1 Text EAGPermissions
639 1 Text ORGPermissions
640 1 Text Automation_Flag
641 1 Text ANDPermissions
642 1 Text RELPermissions
643 1 Text NXXPermissions
644 1 Text ORCPermissions
645 1 Text APRPermissions
646 1 Text CAGPermissions
647 1 Text CARPermissions
648 1 Text CSEPermissions
649 1 Text DAPPermissions
650 1 Text EAPPermissions
651 1 Text ENOPermissions
652 1 Text GNAPermissions
653 1 Text NOFPermissions
654 1 Text ROCPermissions
655 1 Text SAPPermissions
656 1 Text CCIPermissions
657 1 Text NCOPermissions
658 1 Text NMVPermissions
659 1 Text NXLPermissions
660 1 Text ROIPermissions
661 1 Text BBMPermissions
662 1 Text SRCPermissions
663 3 numeric CountofUserEmailAddresses
666 120 Text UserEmailAddress
786 1 Text GSAPermissions
787 1 Text SECPermissions
788 1 Text SUDPermissions
789 1 Text SEPPermissions
790 1 Text STDPermissions
791 1 Text DUCPermissions
792 1 Text NUCPermissions
793 1 Text CASPermissions
794 1 Text DDTPermissions
795 1 Text PRTPermissions
796 1 Text TCOPermissions
797 1 Text LCNPermissions
798 1 Text LRNPermissions
799 1 Text NCNPermissions
800 1 Text NETPermissions
801 1 Text NRNPermissions
802 1 Text MATPermissions
803 1 Text SIDPermissions
804 1 Text SSPPermissions
805 1 Text COSPermissions
806 1 Text CPNPermissions
807 1 Text PRCPermissions
808 1 Text PRLPermissions
809 1 Text NRCPermissions
810 1 Text NRLPermissions
811 1 Text SPSPermissions
812 1 Text GANPermissions
813 1 Text GUNPermissions
814 1 Text SPOPermissions
815 1 Text CPSPermissions
816 4 Text Telco
820 1 Text RECPermissions
821 1 Text AIRPermissions
822 1 Text CIRPermissions
823 1 Text HPUPermissions
824 1 Text OCNPermissions
825 1 Text CLAPermissions
826 1 Text CLEPermissions
827 1 Text NCCPermissions
828 1 Text NLAPermissions
829 1 Text NLEPermissions
830 1 Text NCAPermissions
831 1 Text RACPermissions
832 1 Text RDCPermissions
833 1 Text ENAPermissions
834 1 Text CRSPermissions
835 1 Text CRBPermissions
836 1 Text NACPermissions
837 1 Text CPFPermissions
838 1 Text RMSPermissions
839 1 Text WRAPermissions
840 1 Text LUIPermissions
841 1 Text PADPermissions
842 1 Text TADPermissions
843 1 Text TALPermissions
844 1 Text TECPermissions
845 1 Text TRLPermissions
846 4 trailer ITOCTrailer
*/
package com.smsnow.perf;

import com.smsnow.adaptation.protocol.Protocol;
import com.smsnow.adaptation.dto.ITOCResponse;
import java.io.Serializable;
import com.smsnow.adaptation.protocol.Format;
import com.smsnow.adaptation.protocol.Attribute;
import com.smsnow.adaptation.dto.ITOCTrailer;

@Protocol(name = "ITOCLOGINRESPONSE")
public class ITOCLoginResponse extends ITOCResponse implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.TEXT, offset = 655, length = 1, constant = "")
	private String sAPPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 828, length = 1, constant = "")
	private String nLAPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 662, length = 1, constant = "")
	private String sRCPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 837, length = 1, constant = "")
	private String cPFPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 467, length = 30, constant = "")
	private String userName = "";
	@Format(attribute = Attribute.TEXT, offset = 793, length = 1, constant = "")
	private String cASPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 637, length = 1, constant = "")
	private String nPAPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 625, length = 1, constant = "")
	private String nUSPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 789, length = 1, constant = "")
	private String sEPPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 830, length = 1, constant = "")
	private String nCAPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 808, length = 1, constant = "")
	private String pRLPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 612, length = 1, constant = "")
	private String userClass = "";
	@Format(attribute = Attribute.TEXT, offset = 800, length = 1, constant = "")
	private String nETPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 627, length = 1, constant = "")
	private String cPRPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 845, length = 1, constant = "")
	private String tRLPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 811, length = 1, constant = "")
	private String sPSPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 838, length = 1, constant = "")
	private String rMSPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 661, length = 1, constant = "")
	private String bBMPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 833, length = 1, constant = "")
	private String eNAPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 822, length = 1, constant = "")
	private String cIRPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 840, length = 1, constant = "")
	private String lUIPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 807, length = 1, constant = "")
	private String pRCPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 796, length = 1, constant = "")
	private String tCOPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 458, length = 8, constant = "")
	private String userLogonID = "";
	@Format(attribute = Attribute.TEXT, offset = 644, length = 1, constant = "")
	private String oRCPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 799, length = 1, constant = "")
	private String nCNPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 562, length = 50, constant = "")
	private String viewList = "";
	@Format(attribute = Attribute.TEXT, offset = 666, length = 120, constant = "")
	private String userEmailAddress = "";
	@Format(attribute = Attribute.TEXT, offset = 790, length = 1, constant = "")
	private String sTDPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 834, length = 1, constant = "")
	private String cRSPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 788, length = 1, constant = "")
	private String sUDPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 654, length = 1, constant = "")
	private String rOCPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 646, length = 1, constant = "")
	private String cAGPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 815, length = 1, constant = "")
	private String cPSPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 805, length = 1, constant = "")
	private String cOSPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 835, length = 1, constant = "")
	private String cRBPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 629, length = 1, constant = "")
	private String tRQPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 638, length = 1, constant = "")
	private String eAGPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 645, length = 1, constant = "")
	private String aPRPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 636, length = 1, constant = "")
	private String cRRPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 827, length = 1, constant = "")
	private String nCCPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 841, length = 1, constant = "")
	private String pADPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 831, length = 1, constant = "")
	private String rACPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 641, length = 1, constant = "")
	private String aNDPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 656, length = 1, constant = "")
	private String cCIPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 826, length = 1, constant = "")
	private String cLEPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 648, length = 1, constant = "")
	private String cSEPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 659, length = 1, constant = "")
	private String nXLPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 816, length = 4, constant = "")
	private String telco = "";
	@Format(attribute = Attribute.TEXT, offset = 649, length = 1, constant = "")
	private String dAPPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 801, length = 1, constant = "")
	private String nRNPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 613, length = 8, constant = "")
	private String userGroup = "";
	@Format(attribute = Attribute.TEXT, offset = 844, length = 1, constant = "")
	private String tECPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 507, length = 5, constant = "")
	private String respOrg = "";
	@Format(attribute = Attribute.TEXT, offset = 639, length = 1, constant = "")
	private String oRGPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 820, length = 1, constant = "")
	private String rECPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 842, length = 1, constant = "")
	private String tADPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 798, length = 1, constant = "")
	private String lRNPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 512, length = 50, constant = "")
	private String updateList = "";
	@Format(attribute = Attribute.TEXT, offset = 832, length = 1, constant = "")
	private String rDCPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 836, length = 1, constant = "")
	private String nACPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 642, length = 1, constant = "")
	private String rELPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 466, length = 1, constant = "")
	private String logonStatus = "";
	@Format(attribute = Attribute.TEXT, offset = 657, length = 1, constant = "")
	private String nCOPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 640, length = 1, constant = "")
	private String automation_Flag = "";
	@Format(attribute = Attribute.TEXT, offset = 628, length = 1, constant = "")
	private String lADPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 806, length = 1, constant = "")
	private String cPNPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 813, length = 1, constant = "")
	private String gUNPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 786, length = 1, constant = "")
	private String gSAPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 635, length = 1, constant = "")
	private String cRAPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 810, length = 1, constant = "")
	private String nRLPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 825, length = 1, constant = "")
	private String cLAPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 630, length = 1, constant = "")
	private String aOSLabelPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 829, length = 1, constant = "")
	private String nLEPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 634, length = 1, constant = "")
	private String fCC_Flag = "";
	@Format(attribute = Attribute.TEXT, offset = 821, length = 1, constant = "")
	private String aIRPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 643, length = 1, constant = "")
	private String nXXPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 812, length = 1, constant = "")
	private String gANPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 797, length = 1, constant = "")
	private String lCNPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 794, length = 1, constant = "")
	private String dDTPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 809, length = 1, constant = "")
	private String nRCPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 824, length = 1, constant = "")
	private String oCNPermissions = "";
	@Format(attribute = Attribute.TRAILER, offset = 846, length = 4, constant = "")
	private ITOCTrailer iTOCTrailer = null;
	@Format(attribute = Attribute.NUMERIC, offset = 631, length = 3, constant = "")
	private int timeoutInterval;
	@Format(attribute = Attribute.TEXT, offset = 647, length = 1, constant = "")
	private String cARPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 626, length = 1, constant = "")
	private String cADPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 791, length = 1, constant = "")
	private String dUCPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 792, length = 1, constant = "")
	private String nUCPermissions = "";
	@Format(attribute = Attribute.NUMERIC, offset = 621, length = 4, constant = "")
	private int maximumLogonAttempts;
	@Format(attribute = Attribute.TEXT, offset = 658, length = 1, constant = "")
	private String nMVPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 653, length = 1, constant = "")
	private String nOFPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 652, length = 1, constant = "")
	private String gNAPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 795, length = 1, constant = "")
	private String pRTPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 802, length = 1, constant = "")
	private String mATPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 803, length = 1, constant = "")
	private String sIDPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 660, length = 1, constant = "")
	private String rOIPermissions = "";
	@Format(attribute = Attribute.NUMERIC, offset = 663, length = 3, constant = "")
	private int countofUserEmailAddresses;
	@Format(attribute = Attribute.TEXT, offset = 497, length = 10, constant = "")
	private String userPhone = "";
	@Format(attribute = Attribute.TEXT, offset = 651, length = 1, constant = "")
	private String eNOPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 650, length = 1, constant = "")
	private String eAPPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 804, length = 1, constant = "")
	private String sSPPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 823, length = 1, constant = "")
	private String hPUPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 814, length = 1, constant = "")
	private String sPOPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 839, length = 1, constant = "")
	private String wRAPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 843, length = 1, constant = "")
	private String tALPermissions = "";
	@Format(attribute = Attribute.TEXT, offset = 787, length = 1, constant = "")
	private String sECPermissions = "";

	public String getSAPPermissions() {
		return sAPPermissions;
	}

	public void setSAPPermissions(String sAPPermissions) {
		this.sAPPermissions = sAPPermissions;
	}

	public String getNLAPermissions() {
		return nLAPermissions;
	}

	public void setNLAPermissions(String nLAPermissions) {
		this.nLAPermissions = nLAPermissions;
	}

	public String getSRCPermissions() {
		return sRCPermissions;
	}

	public void setSRCPermissions(String sRCPermissions) {
		this.sRCPermissions = sRCPermissions;
	}

	public String getCPFPermissions() {
		return cPFPermissions;
	}

	public void setCPFPermissions(String cPFPermissions) {
		this.cPFPermissions = cPFPermissions;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getCASPermissions() {
		return cASPermissions;
	}

	public void setCASPermissions(String cASPermissions) {
		this.cASPermissions = cASPermissions;
	}

	public String getNPAPermissions() {
		return nPAPermissions;
	}

	public void setNPAPermissions(String nPAPermissions) {
		this.nPAPermissions = nPAPermissions;
	}

	public String getNUSPermissions() {
		return nUSPermissions;
	}

	public void setNUSPermissions(String nUSPermissions) {
		this.nUSPermissions = nUSPermissions;
	}

	public String getSEPPermissions() {
		return sEPPermissions;
	}

	public void setSEPPermissions(String sEPPermissions) {
		this.sEPPermissions = sEPPermissions;
	}

	public String getNCAPermissions() {
		return nCAPermissions;
	}

	public void setNCAPermissions(String nCAPermissions) {
		this.nCAPermissions = nCAPermissions;
	}

	public String getPRLPermissions() {
		return pRLPermissions;
	}

	public void setPRLPermissions(String pRLPermissions) {
		this.pRLPermissions = pRLPermissions;
	}

	public String getUserClass() {
		return userClass;
	}

	public void setUserClass(String userClass) {
		this.userClass = userClass;
	}

	public String getNETPermissions() {
		return nETPermissions;
	}

	public void setNETPermissions(String nETPermissions) {
		this.nETPermissions = nETPermissions;
	}

	public String getCPRPermissions() {
		return cPRPermissions;
	}

	public void setCPRPermissions(String cPRPermissions) {
		this.cPRPermissions = cPRPermissions;
	}

	public String getTRLPermissions() {
		return tRLPermissions;
	}

	public void setTRLPermissions(String tRLPermissions) {
		this.tRLPermissions = tRLPermissions;
	}

	public String getSPSPermissions() {
		return sPSPermissions;
	}

	public void setSPSPermissions(String sPSPermissions) {
		this.sPSPermissions = sPSPermissions;
	}

	public String getRMSPermissions() {
		return rMSPermissions;
	}

	public void setRMSPermissions(String rMSPermissions) {
		this.rMSPermissions = rMSPermissions;
	}

	public String getBBMPermissions() {
		return bBMPermissions;
	}

	public void setBBMPermissions(String bBMPermissions) {
		this.bBMPermissions = bBMPermissions;
	}

	public String getENAPermissions() {
		return eNAPermissions;
	}

	public void setENAPermissions(String eNAPermissions) {
		this.eNAPermissions = eNAPermissions;
	}

	public String getCIRPermissions() {
		return cIRPermissions;
	}

	public void setCIRPermissions(String cIRPermissions) {
		this.cIRPermissions = cIRPermissions;
	}

	public String getLUIPermissions() {
		return lUIPermissions;
	}

	public void setLUIPermissions(String lUIPermissions) {
		this.lUIPermissions = lUIPermissions;
	}

	public String getPRCPermissions() {
		return pRCPermissions;
	}

	public void setPRCPermissions(String pRCPermissions) {
		this.pRCPermissions = pRCPermissions;
	}

	public String getTCOPermissions() {
		return tCOPermissions;
	}

	public void setTCOPermissions(String tCOPermissions) {
		this.tCOPermissions = tCOPermissions;
	}

	public String getUserLogonID() {
		return userLogonID;
	}

	public void setUserLogonID(String userLogonID) {
		this.userLogonID = userLogonID;
	}

	public String getORCPermissions() {
		return oRCPermissions;
	}

	public void setORCPermissions(String oRCPermissions) {
		this.oRCPermissions = oRCPermissions;
	}

	public String getNCNPermissions() {
		return nCNPermissions;
	}

	public void setNCNPermissions(String nCNPermissions) {
		this.nCNPermissions = nCNPermissions;
	}

	public String getViewList() {
		return viewList;
	}

	public void setViewList(String viewList) {
		this.viewList = viewList;
	}

	public String getUserEmailAddress() {
		return userEmailAddress;
	}

	public void setUserEmailAddress(String userEmailAddress) {
		this.userEmailAddress = userEmailAddress;
	}

	public String getSTDPermissions() {
		return sTDPermissions;
	}

	public void setSTDPermissions(String sTDPermissions) {
		this.sTDPermissions = sTDPermissions;
	}

	public String getCRSPermissions() {
		return cRSPermissions;
	}

	public void setCRSPermissions(String cRSPermissions) {
		this.cRSPermissions = cRSPermissions;
	}

	public String getSUDPermissions() {
		return sUDPermissions;
	}

	public void setSUDPermissions(String sUDPermissions) {
		this.sUDPermissions = sUDPermissions;
	}

	public String getROCPermissions() {
		return rOCPermissions;
	}

	public void setROCPermissions(String rOCPermissions) {
		this.rOCPermissions = rOCPermissions;
	}

	public String getCAGPermissions() {
		return cAGPermissions;
	}

	public void setCAGPermissions(String cAGPermissions) {
		this.cAGPermissions = cAGPermissions;
	}

	public String getCPSPermissions() {
		return cPSPermissions;
	}

	public void setCPSPermissions(String cPSPermissions) {
		this.cPSPermissions = cPSPermissions;
	}

	public String getCOSPermissions() {
		return cOSPermissions;
	}

	public void setCOSPermissions(String cOSPermissions) {
		this.cOSPermissions = cOSPermissions;
	}

	public String getCRBPermissions() {
		return cRBPermissions;
	}

	public void setCRBPermissions(String cRBPermissions) {
		this.cRBPermissions = cRBPermissions;
	}

	public String getTRQPermissions() {
		return tRQPermissions;
	}

	public void setTRQPermissions(String tRQPermissions) {
		this.tRQPermissions = tRQPermissions;
	}

	public String getEAGPermissions() {
		return eAGPermissions;
	}

	public void setEAGPermissions(String eAGPermissions) {
		this.eAGPermissions = eAGPermissions;
	}

	public String getAPRPermissions() {
		return aPRPermissions;
	}

	public void setAPRPermissions(String aPRPermissions) {
		this.aPRPermissions = aPRPermissions;
	}

	public String getCRRPermissions() {
		return cRRPermissions;
	}

	public void setCRRPermissions(String cRRPermissions) {
		this.cRRPermissions = cRRPermissions;
	}

	public String getNCCPermissions() {
		return nCCPermissions;
	}

	public void setNCCPermissions(String nCCPermissions) {
		this.nCCPermissions = nCCPermissions;
	}

	public String getPADPermissions() {
		return pADPermissions;
	}

	public void setPADPermissions(String pADPermissions) {
		this.pADPermissions = pADPermissions;
	}

	public String getRACPermissions() {
		return rACPermissions;
	}

	public void setRACPermissions(String rACPermissions) {
		this.rACPermissions = rACPermissions;
	}

	public String getANDPermissions() {
		return aNDPermissions;
	}

	public void setANDPermissions(String aNDPermissions) {
		this.aNDPermissions = aNDPermissions;
	}

	public String getCCIPermissions() {
		return cCIPermissions;
	}

	public void setCCIPermissions(String cCIPermissions) {
		this.cCIPermissions = cCIPermissions;
	}

	public String getCLEPermissions() {
		return cLEPermissions;
	}

	public void setCLEPermissions(String cLEPermissions) {
		this.cLEPermissions = cLEPermissions;
	}

	public String getCSEPermissions() {
		return cSEPermissions;
	}

	public void setCSEPermissions(String cSEPermissions) {
		this.cSEPermissions = cSEPermissions;
	}

	public String getNXLPermissions() {
		return nXLPermissions;
	}

	public void setNXLPermissions(String nXLPermissions) {
		this.nXLPermissions = nXLPermissions;
	}

	public String getTelco() {
		return telco;
	}

	public void setTelco(String telco) {
		this.telco = telco;
	}

	public String getDAPPermissions() {
		return dAPPermissions;
	}

	public void setDAPPermissions(String dAPPermissions) {
		this.dAPPermissions = dAPPermissions;
	}

	public String getNRNPermissions() {
		return nRNPermissions;
	}

	public void setNRNPermissions(String nRNPermissions) {
		this.nRNPermissions = nRNPermissions;
	}

	public String getUserGroup() {
		return userGroup;
	}

	public void setUserGroup(String userGroup) {
		this.userGroup = userGroup;
	}

	public String getTECPermissions() {
		return tECPermissions;
	}

	public void setTECPermissions(String tECPermissions) {
		this.tECPermissions = tECPermissions;
	}

	public String getRespOrg() {
		return respOrg;
	}

	public void setRespOrg(String respOrg) {
		this.respOrg = respOrg;
	}

	public String getORGPermissions() {
		return oRGPermissions;
	}

	public void setORGPermissions(String oRGPermissions) {
		this.oRGPermissions = oRGPermissions;
	}

	public String getRECPermissions() {
		return rECPermissions;
	}

	public void setRECPermissions(String rECPermissions) {
		this.rECPermissions = rECPermissions;
	}

	public String getTADPermissions() {
		return tADPermissions;
	}

	public void setTADPermissions(String tADPermissions) {
		this.tADPermissions = tADPermissions;
	}

	public String getLRNPermissions() {
		return lRNPermissions;
	}

	public void setLRNPermissions(String lRNPermissions) {
		this.lRNPermissions = lRNPermissions;
	}

	public String getUpdateList() {
		return updateList;
	}

	public void setUpdateList(String updateList) {
		this.updateList = updateList;
	}

	public String getRDCPermissions() {
		return rDCPermissions;
	}

	public void setRDCPermissions(String rDCPermissions) {
		this.rDCPermissions = rDCPermissions;
	}

	public String getNACPermissions() {
		return nACPermissions;
	}

	public void setNACPermissions(String nACPermissions) {
		this.nACPermissions = nACPermissions;
	}

	public String getRELPermissions() {
		return rELPermissions;
	}

	public void setRELPermissions(String rELPermissions) {
		this.rELPermissions = rELPermissions;
	}

	public String getLogonStatus() {
		return logonStatus;
	}

	public void setLogonStatus(String logonStatus) {
		this.logonStatus = logonStatus;
	}

	public String getNCOPermissions() {
		return nCOPermissions;
	}

	public void setNCOPermissions(String nCOPermissions) {
		this.nCOPermissions = nCOPermissions;
	}

	public String getAutomation_Flag() {
		return automation_Flag;
	}

	public void setAutomation_Flag(String automation_Flag) {
		this.automation_Flag = automation_Flag;
	}

	public String getLADPermissions() {
		return lADPermissions;
	}

	public void setLADPermissions(String lADPermissions) {
		this.lADPermissions = lADPermissions;
	}

	public String getCPNPermissions() {
		return cPNPermissions;
	}

	public void setCPNPermissions(String cPNPermissions) {
		this.cPNPermissions = cPNPermissions;
	}

	public String getGUNPermissions() {
		return gUNPermissions;
	}

	public void setGUNPermissions(String gUNPermissions) {
		this.gUNPermissions = gUNPermissions;
	}

	public String getGSAPermissions() {
		return gSAPermissions;
	}

	public void setGSAPermissions(String gSAPermissions) {
		this.gSAPermissions = gSAPermissions;
	}

	public String getCRAPermissions() {
		return cRAPermissions;
	}

	public void setCRAPermissions(String cRAPermissions) {
		this.cRAPermissions = cRAPermissions;
	}

	public String getNRLPermissions() {
		return nRLPermissions;
	}

	public void setNRLPermissions(String nRLPermissions) {
		this.nRLPermissions = nRLPermissions;
	}

	public String getCLAPermissions() {
		return cLAPermissions;
	}

	public void setCLAPermissions(String cLAPermissions) {
		this.cLAPermissions = cLAPermissions;
	}

	public String getAOSLabelPermissions() {
		return aOSLabelPermissions;
	}

	public void setAOSLabelPermissions(String aOSLabelPermissions) {
		this.aOSLabelPermissions = aOSLabelPermissions;
	}

	public String getNLEPermissions() {
		return nLEPermissions;
	}

	public void setNLEPermissions(String nLEPermissions) {
		this.nLEPermissions = nLEPermissions;
	}

	public String getFCC_Flag() {
		return fCC_Flag;
	}

	public void setFCC_Flag(String fCC_Flag) {
		this.fCC_Flag = fCC_Flag;
	}

	public String getAIRPermissions() {
		return aIRPermissions;
	}

	public void setAIRPermissions(String aIRPermissions) {
		this.aIRPermissions = aIRPermissions;
	}

	public String getNXXPermissions() {
		return nXXPermissions;
	}

	public void setNXXPermissions(String nXXPermissions) {
		this.nXXPermissions = nXXPermissions;
	}

	public String getGANPermissions() {
		return gANPermissions;
	}

	public void setGANPermissions(String gANPermissions) {
		this.gANPermissions = gANPermissions;
	}

	public String getLCNPermissions() {
		return lCNPermissions;
	}

	public void setLCNPermissions(String lCNPermissions) {
		this.lCNPermissions = lCNPermissions;
	}

	public String getDDTPermissions() {
		return dDTPermissions;
	}

	public void setDDTPermissions(String dDTPermissions) {
		this.dDTPermissions = dDTPermissions;
	}

	public String getNRCPermissions() {
		return nRCPermissions;
	}

	public void setNRCPermissions(String nRCPermissions) {
		this.nRCPermissions = nRCPermissions;
	}

	public String getOCNPermissions() {
		return oCNPermissions;
	}

	public void setOCNPermissions(String oCNPermissions) {
		this.oCNPermissions = oCNPermissions;
	}

	public ITOCTrailer getITOCTrailer() {
		return iTOCTrailer;
	}

	public void setITOCTrailer(ITOCTrailer iTOCTrailer) {
		this.iTOCTrailer = iTOCTrailer;
	}

	public int getTimeoutInterval() {
		return timeoutInterval;
	}

	public void setTimeoutInterval(int timeoutInterval) {
		this.timeoutInterval = timeoutInterval;
	}

	public String getCARPermissions() {
		return cARPermissions;
	}

	public void setCARPermissions(String cARPermissions) {
		this.cARPermissions = cARPermissions;
	}

	public String getCADPermissions() {
		return cADPermissions;
	}

	public void setCADPermissions(String cADPermissions) {
		this.cADPermissions = cADPermissions;
	}

	public String getDUCPermissions() {
		return dUCPermissions;
	}

	public void setDUCPermissions(String dUCPermissions) {
		this.dUCPermissions = dUCPermissions;
	}

	public String getNUCPermissions() {
		return nUCPermissions;
	}

	public void setNUCPermissions(String nUCPermissions) {
		this.nUCPermissions = nUCPermissions;
	}

	public int getMaximumLogonAttempts() {
		return maximumLogonAttempts;
	}

	public void setMaximumLogonAttempts(int maximumLogonAttempts) {
		this.maximumLogonAttempts = maximumLogonAttempts;
	}

	public String getNMVPermissions() {
		return nMVPermissions;
	}

	public void setNMVPermissions(String nMVPermissions) {
		this.nMVPermissions = nMVPermissions;
	}

	public String getNOFPermissions() {
		return nOFPermissions;
	}

	public void setNOFPermissions(String nOFPermissions) {
		this.nOFPermissions = nOFPermissions;
	}

	public String getGNAPermissions() {
		return gNAPermissions;
	}

	public void setGNAPermissions(String gNAPermissions) {
		this.gNAPermissions = gNAPermissions;
	}

	public String getPRTPermissions() {
		return pRTPermissions;
	}

	public void setPRTPermissions(String pRTPermissions) {
		this.pRTPermissions = pRTPermissions;
	}

	public String getMATPermissions() {
		return mATPermissions;
	}

	public void setMATPermissions(String mATPermissions) {
		this.mATPermissions = mATPermissions;
	}

	public String getSIDPermissions() {
		return sIDPermissions;
	}

	public void setSIDPermissions(String sIDPermissions) {
		this.sIDPermissions = sIDPermissions;
	}

	public String getROIPermissions() {
		return rOIPermissions;
	}

	public void setROIPermissions(String rOIPermissions) {
		this.rOIPermissions = rOIPermissions;
	}

	public int getCountofUserEmailAddresses() {
		return countofUserEmailAddresses;
	}

	public void setCountofUserEmailAddresses(int countofUserEmailAddresses) {
		this.countofUserEmailAddresses = countofUserEmailAddresses;
	}

	public String getUserPhone() {
		return userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public String getENOPermissions() {
		return eNOPermissions;
	}

	public void setENOPermissions(String eNOPermissions) {
		this.eNOPermissions = eNOPermissions;
	}

	public String getEAPPermissions() {
		return eAPPermissions;
	}

	public void setEAPPermissions(String eAPPermissions) {
		this.eAPPermissions = eAPPermissions;
	}

	public String getSSPPermissions() {
		return sSPPermissions;
	}

	public void setSSPPermissions(String sSPPermissions) {
		this.sSPPermissions = sSPPermissions;
	}

	public String getHPUPermissions() {
		return hPUPermissions;
	}

	public void setHPUPermissions(String hPUPermissions) {
		this.hPUPermissions = hPUPermissions;
	}

	public String getSPOPermissions() {
		return sPOPermissions;
	}

	public void setSPOPermissions(String sPOPermissions) {
		this.sPOPermissions = sPOPermissions;
	}

	public String getWRAPermissions() {
		return wRAPermissions;
	}

	public void setWRAPermissions(String wRAPermissions) {
		this.wRAPermissions = wRAPermissions;
	}

	public String getTALPermissions() {
		return tALPermissions;
	}

	public void setTALPermissions(String tALPermissions) {
		this.tALPermissions = tALPermissions;
	}

	public String getSECPermissions() {
		return sECPermissions;
	}

	public void setSECPermissions(String sECPermissions) {
		this.sECPermissions = sECPermissions;
	}

	public ITOCLoginResponse() {
		super();
	}
}