/* Generated by SMSNOW protocol CodeGen on Wed Aug 03 17:28:22 IST 2016. 

412 8 Text UserLogonID
420 8 Text UserPassword
428 8 Text OldPassword
436 1 Text Action
437 4 trailer ITOCTrailer
*/
package com.smsnow.perf;

import com.smsnow.adaptation.protocol.Protocol;
import com.smsnow.adaptation.dto.ITOCRequest;
import java.io.Serializable;
import com.smsnow.adaptation.protocol.Format;
import com.smsnow.adaptation.protocol.Attribute;
import com.smsnow.adaptation.dto.ITOCTrailer;

@Protocol(name = "ITOCLOGIN")
public class ITOCLogin extends ITOCRequest implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.TEXT, offset = 420, length = 8, constant = "")
	private String userPassword = "";
	@Format(attribute = Attribute.TEXT, offset = 428, length = 8, constant = "")
	private String oldPassword = "";
	@Format(attribute = Attribute.TEXT, offset = 436, length = 1, constant = "")
	private String action = "";
	@Format(attribute = Attribute.TRAILER, offset = 437, length = 4, constant = "")
	private ITOCTrailer iTOCTrailer = null;
	@Format(attribute = Attribute.TEXT, offset = 412, length = 8, constant = "")
	private String userLogonID = "";

	public String getUserPassword() {
		return userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getOldPassword() {
		return oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public ITOCTrailer getITOCTrailer() {
		return iTOCTrailer;
	}

	public void setITOCTrailer(ITOCTrailer iTOCTrailer) {
		this.iTOCTrailer = iTOCTrailer;
	}

	public String getUserLogonID() {
		return userLogonID;
	}

	public void setUserLogonID(String userLogonID) {
		this.userLogonID = userLogonID;
	}

	public ITOCLogin() {
	}

	public ITOCLogin(String string) {
		setUserLogonID(string);
	}
}