/* Generated by SMSNOW protocol CodeGen on Wed Aug 03 16:24:21 IST 2016. 

458 8 Text UserLogonID
466 1 Text LogoffStatus
467 4 trailer ITOCTrailerRecord
*/
package com.reactiva.protoserver;

import com.smsnow.adaptation.protocol.Protocol;

import java.io.Serializable;
import com.smsnow.adaptation.protocol.Format;
import com.smsnow.adaptation.dto.ITOCResponse;
import com.smsnow.adaptation.dto.ITOCTrailer;
import com.smsnow.adaptation.protocol.Attribute;

@Protocol(name = "LOGOFFRESPONSE")
public class LogoffResponse extends ITOCResponse implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.TEXT, offset = 466, length = 1, constant = "")
	private String logoffStatus = "";
	@Format(attribute = Attribute.TRAILER, offset = 467, length = 4, constant = "")
	private ITOCTrailer iTOCTrailerRecord = null;
	@Format(attribute = Attribute.TEXT, offset = 458, length = 8, constant = "")
	private String userLogonID = "";

	public String getLogoffStatus() {
		return logoffStatus;
	}

	public void setLogoffStatus(String logoffStatus) {
		this.logoffStatus = logoffStatus;
	}

	public ITOCTrailer getITOCTrailerRecord() {
		return iTOCTrailerRecord;
	}

	public void setITOCTrailerRecord(ITOCTrailer iTOCTrailerRecord) {
		this.iTOCTrailerRecord = iTOCTrailerRecord;
	}

	public String getUserLogonID() {
		return userLogonID;
	}

	public void setUserLogonID(String userLogonID) {
		this.userLogonID = userLogonID;
	}

	public LogoffResponse() {
	}
}