/* Generated by SMSNOW protocol CodeGen on Wed Aug 03 16:25:52 IST 2016. 

412 8 Text UserLogonID
420 4 trailer ITOCTrailerRecord
*/
package com.reactiva.protoserver;

import com.smsnow.adaptation.protocol.Protocol;

import java.io.Serializable;

import com.smsnow.adaptation.protocol.Format;
import com.smsnow.adaptation.dto.ITOCRequest;
import com.smsnow.adaptation.dto.ITOCTrailer;
import com.smsnow.adaptation.protocol.Attribute;

@Protocol(name = "LOGOFFREQUEST")
public class LogoffRequest extends ITOCRequest implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.TRAILER, offset = 420, length = 4, constant = "")
	private ITOCTrailer iTOCTrailerRecord = null;
	@Format(attribute = Attribute.TEXT, offset = 412, length = 8, constant = "")
	private String userLogonID = "";

	public ITOCTrailer getITOCTrailerRecord() {
		return iTOCTrailerRecord;
	}

	public void setITOCTrailerRecord(ITOCTrailer iTOCTrailerRecord) {
		this.iTOCTrailerRecord = iTOCTrailerRecord;
	}

	public String getUserLogonID() {
		return userLogonID;
	}

	public void setUserLogonID(String userLogonID) {
		this.userLogonID = userLogonID;
	}

	public LogoffRequest() {
	}
}