/* Generated by SMSNOW protocol CodeGen on Wed Aug 03 16:21:24 IST 2016. 

0 154 outheader MVSOutboundITOCHeader
154 304 appheader ApplicationHeader
*/
package com.smsnow.adaptation.dto;

import com.smsnow.adaptation.protocol.Protocol;
import java.io.Serializable;

import com.smsnow.adaptation.protocol.Format;
import com.smsnow.adaptation.dto.ApplicationHeader;
import com.smsnow.adaptation.dto.ITOCOutboundHeader;
import com.smsnow.adaptation.protocol.Attribute;

@Protocol(name = "ITOCRESPONSE")
public class ITOCResponse implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.APPHEADER, offset = 154, length = 304, constant = "")
	private ApplicationHeader applicationHeader = null;
	@Format(attribute = Attribute.OUTHEADER, offset = 0, length = 154, constant = "")
	private ITOCOutboundHeader mVSOutboundITOCHeader = null;

	public ApplicationHeader getApplicationHeader() {
		return applicationHeader;
	}

	public void setApplicationHeader(ApplicationHeader applicationHeader) {
		this.applicationHeader = applicationHeader;
	}

	public ITOCOutboundHeader getMVSOutboundITOCHeader() {
		return mVSOutboundITOCHeader;
	}

	public void setMVSOutboundITOCHeader(
			ITOCOutboundHeader mVSOutboundITOCHeader) {
		this.mVSOutboundITOCHeader = mVSOutboundITOCHeader;
	}

	public ITOCResponse() {
	}
}