/* Generated by SMSNOW protocol CodeGen on Wed Aug 03 16:22:47 IST 2016. 

0 108 * MVSInboundITOCHeader
108 304 * ApplicationHeader
*/
package com.smsnow.adaptation.dto;

import com.smsnow.adaptation.protocol.Protocol;
import java.io.Serializable;
import com.smsnow.adaptation.protocol.Format;
import com.smsnow.adaptation.protocol.Attribute;

@Protocol(name = "ITOCREQUEST")
public class ITOCRequest implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.UNDEF, offset = 108, length = 304, constant = "")
	private byte[] applicationHeader = new byte[304];
	@Format(attribute = Attribute.UNDEF, offset = 0, length = 108, constant = "")
	private byte[] mVSInboundITOCHeader = new byte[108];

	public byte[] getApplicationHeader() {
		return applicationHeader;
	}

	public void setApplicationHeader(byte[] applicationHeader) {
		this.applicationHeader = applicationHeader;
	}

	public byte[] getMVSInboundITOCHeader() {
		return mVSInboundITOCHeader;
	}

	public void setMVSInboundITOCHeader(byte[] mVSInboundITOCHeader) {
		this.mVSInboundITOCHeader = mVSInboundITOCHeader;
	}

	public ITOCRequest() {
	}
}