/* Generated by SMSNOW protocol CodeGen on Wed Aug 03 13:29:52 IST 2016. 

0 108 inheader MVSInboundITOCHeader
108 304 appheader ApplicationHeader
412 8 Text UserLogonID
420 4 trailer ITOCTrailerRecord
*/
package com.smsnow.adaptation.dto;

import com.smsnow.adaptation.protocol.Protocol;
import java.io.Serializable;

import com.smsnow.adaptation.protocol.Format;
import com.smsnow.adaptation.dto.common.ApplicationHeader;
import com.smsnow.adaptation.dto.common.ITOCInboundHeader;
import com.smsnow.adaptation.dto.common.ITOCTrailer;
import com.smsnow.adaptation.protocol.Attribute;

@Protocol(name = "LOGOFFREQUEST")
public class LogoffRequest implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.APPHEADER, offset = 108, length = 304, constant = "")
	private ApplicationHeader applicationHeader;
	@Format(attribute = Attribute.TRAILER, offset = 420, length = 4, constant = "")
	private ITOCTrailer iTOCTrailerRecord;
	@Format(attribute = Attribute.INHEADER, offset = 0, length = 108, constant = "")
	private ITOCInboundHeader mVSInboundITOCHeader;
	@Format(attribute = Attribute.TEXT, offset = 412, length = 8, constant = "")
	private String userLogonID;

	public ApplicationHeader getApplicationHeader() {
		return applicationHeader;
	}

	public void setApplicationHeader(ApplicationHeader applicationHeader) {
		this.applicationHeader = applicationHeader;
	}

	public ITOCTrailer getITOCTrailerRecord() {
		return iTOCTrailerRecord;
	}

	public void setITOCTrailerRecord(ITOCTrailer iTOCTrailerRecord) {
		this.iTOCTrailerRecord = iTOCTrailerRecord;
	}

	public ITOCInboundHeader getMVSInboundITOCHeader() {
		return mVSInboundITOCHeader;
	}

	public void setMVSInboundITOCHeader(ITOCInboundHeader mVSInboundITOCHeader) {
		this.mVSInboundITOCHeader = mVSInboundITOCHeader;
	}

	public String getUserLogonID() {
		return userLogonID;
	}

	public void setUserLogonID(String userLogonID) {
		this.userLogonID = userLogonID;
	}

	public LogoffRequest() {
	}
}