/* Generated by SMSNOW protocol CodeGen on Mon Aug 01 12:03:40 IST 2016. 

0 154 * MVSOutboundHWSHeader
154 304 * ApplicationHeader
458 8 Text UserLogonID
*/
package com.smsnow.adaptation.server.dto;

import java.io.Serializable;

import com.smsnow.adaptation.protocol.Attribute;
import com.smsnow.adaptation.protocol.Format;
import com.smsnow.adaptation.protocol.Protocol;

@Protocol(name = "ITOCLOGIN")
public class ITOCLogin implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.UNDEF, offset = 0, length = 154, constant = "")
	private byte[] mVSOutboundHWSHeader;
	@Format(attribute = Attribute.UNDEF, offset = 154, length = 304, constant = "")
	private byte[] applicationHeader;
	@Format(attribute = Attribute.TEXT, offset = 458, length = 8, constant = "")
	private String userLogonID;

	@Override
	public String toString() {
		return "ITOCLogin [userLogonID=" + userLogonID + "]";
	}

	public byte[] getMVSOutboundHWSHeader() {
		return mVSOutboundHWSHeader;
	}

	public void setMVSOutboundHWSHeader(byte[] mVSOutboundHWSHeader) {
		this.mVSOutboundHWSHeader = mVSOutboundHWSHeader;
	}

	public byte[] getApplicationHeader() {
		return applicationHeader;
	}

	public void setApplicationHeader(byte[] applicationHeader) {
		this.applicationHeader = applicationHeader;
	}

	public String getUserLogonID() {
		return userLogonID;
	}

	public void setUserLogonID(String userLogonID) {
		this.userLogonID = userLogonID;
	}

	public ITOCLogin(String userLogonID) {
		super();
		this.userLogonID = userLogonID;
	}

	public ITOCLogin() {
	}
}